BOOTLOADER = atmel-dfu
AUTO_SHIFT_ENABLE = yes
OLED_ENABLE = yes
OLED_DRIVER = SSD1306
CONSOLE_ENABLE = no
EXTRAKEY_ENABLE = yes
COMMAND_ENABLE = no
SPLIT_KEYBOARD = yes
NKRO_ENABLE = no            # Enable N-Key Rollover
BACKLIGHT_ENABLE = no       # Enable keyboard backlight functionality
RGBLIGHT_ENABLE = no        # Enable keyboard RGB underglow
BLUETOOTH_ENABLE = no       # Enable Bluetooth
AUDIO_ENABLE = no           # Audio output
MOUSEKEY_ENABLE = no       # Mouse keys
TAP_DANCE_ENABLE = yes
SWAP_HANDS_ENABLE= no
